quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    log:
      sql: true
    database:
      generation: drop-and-create