"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/library
      username: postgres
      password: postgres
    hibernate-orm:
      log:
        sql: true
      database:
        generation: drop-and-create
      sql-load-script: import-dev.sql

"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:~/test
      username: sa
      password:
    hibernate-orm:
      log:
        sql: true
      database:
        generation: drop-and-create
      sql-load-script: import-test.sql