INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (1, 'SPRING FRAMEWORK', '79.99', CURRENT_DATE);
INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (2, 'JAVA 8', '59.99', CURRENT_DATE);
INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (3, 'QUARKUS', '69.99', CURRENT_DATE);