INSERT INTO BOOKS (ID, NAME, PRICE) VALUES (NEXTVAL('SEQ_BOOK'), 'SPRING FRAMEWORK', '79.99');
INSERT INTO BOOKS (ID, NAME, PRICE) VALUES (NEXTVAL('SEQ_BOOK'), 'JAVA 8', '59.99');
INSERT INTO BOOKS (ID, NAME, PRICE) VALUES (NEXTVAL('SEQ_BOOK'), 'QUARKUS', '69.99');