INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (NEXTVAL('SEQ_BOOK'), 'SPRING FRAMEWORK', '79.99', CURRENT_DATE);
INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (NEXTVAL('SEQ_BOOK'), 'JAVA 8', '59.99', CURRENT_DATE);
INSERT INTO BOOKS (ID, NAME, PRICE, REGISTER_AT) VALUES (NEXTVAL('SEQ_BOOK'), 'QUARKUS', '69.99', CURRENT_DATE);